name: AlaHub
version: 1.0
author: Lirobi
main: fr.lirobi.lirobiplugin.MainPlugin
commands:
  test:
    description: commande de test
    permission: test.use
  bc:
    description: commande de broadcast
    permission: bc.use
  hub:
    description: teleportation au spawn
  fly:
    description: fly admin
    permission: fly.use
  msg:
    description: message prive